# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f25355061685b3368791f44b4363fcc771a616a845efb0f308b8238fc2a7f456ec4bb379aca521175b5814b1aca1345a58d0c98476fd60ccfa0c5806acb03976

test:
  secret_key_base: bf61d18a21216ea6958de2600a441dd50ed9bf136ece5c88531e681bc37b7821aa08ef54c8aeb29ed81b3b1e29af7cc580bfcd3a73e60defe1f6078952564e7f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
